### ISSUE TITLE
SyntaxError: Unexpected token u

### ISSUE THREAD

**Issue by mk-pmb** [superpowers-extra/lumberjack-jacques-game#1]
``` text
The server crashed while loading project "lumberjack-jacques-game".
SyntaxError: Unexpected token u
    at Object.parse (native)
    at /…/sp-dev/core/systems/game/plugins/default/sprite/data/SpriteAsset.js:91:36
    at FSReqWrap.oncomplete (fs.js:82:15)
```

What could be next steps to debug or fix this?

``` text
Devel environment: Node.js v5.7.1, npm v3.6.0, Ubuntu 14.04.4 LTS trusty
sp-dev/app = superpowers/superpowers-app @ d0af9ed: Make travis notify gitter
sp-dev/core = superpowers/superpowers-core @ 2f266e9: SupClient: Store client ID on ProjectClient
sp-dev/core/systems/game = superpowers/superpowers-game @ d1ce643: scene: Allow dropping scene in a prefab again. Fixes #79
sp-dev/proj/lumberjack-jacques-game = superpowers-extra/lumberjack-jacques-game @ 3371125: More work on ranged enemies. Add collision in boss room and some ranged enemies
sp-dev/systems/superpowers-love2d = superpowers/superpowers-love2d @ 2867741: README: Add build status badge
```

**Comment by MggMuggins** [comment]
I'd say take a look at SpriteAsset.js line 91, column 36 and see what it's about. Probably an easy-to-fix syntax error.

**Comment by mk-pmb** [comment]
Thanks for the idea. I had ruled that easy idea out at first sight, since I had expected a syntax error in a file to be reported as the first stack frame in the error stack, so back then I didn't care to look. Here's line 91:

```javascript
                        pub = JSON.parse(json);
```

Column 36 is the "p" of "parse", which explains why the first stack frame is "Object.parse (native)".

The lines before that refer to `asset.json` and `sprite.json`, so I'll try to investigate them better. I'll also update Superpowers to see whether the current version gives better clues about how to debug JSON parsing failures for the sprite/asset files.

**Comment by MggMuggins** [comment]
Is it supposed to be passing parse a variable, or a string type?

**Comment by mk-pmb** [comment]
Either I don't understand the question, or it should be "both". That `json` identifier is a variable obviously, and I'd hope it contains a string, as that's what [JSON.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) expects as first argument. `SpriteAsset.js` should catch the error, and report which file the malformed JSON string was read from. If I manage to reproduce the problem with latest Superpowers, I'll report that suggestion to the main repo.

Update: Someone else will have to debug this, as unfortunately I can't get the latest version of superpowers to run. (npm fails to install electron.)

**Comment by ronaldpatino** [comment]
Getting the same error while trying to load the game into SP 5.1.0
